In [67]:
import pandas as pd

people = pd.read_csv("people.csv",parse_dates=['date'])
#data = pd.read_csv("act_train.csv",parse_dates=['date'])
trainSub = pd.read_csv("act_train.csv", parse_dates=['date'])
test = pd.read_csv("act_test.csv",parse_dates=['date'])
act = test['activity_id']

In [68]:
trainSub.head()

,people_id,activity_id,date,activity_category,char_1,char_2,char_3,char_4,char_5,char_6,char_7,char_8,char_9,char_10,outcome
0,ppl_100,act2_1734928,2023-08-26,type 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 76,0
1,ppl_100,act2_2434093,2022-09-27,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,0
2,ppl_100,act2_3404049,2022-09-27,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,0
3,ppl_100,act2_3651215,2023-08-04,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,0
4,ppl_100,act2_4109017,2023-08-26,type 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,type 1,0

In [69]:
from datetime import datetime

trainSub.iloc[0]['date']
#trainSub['date'] = datetime.strptime(trainSub['date'], '%Y-%m-%d')

Timestamp('2023-08-26 00:00:00')

In [70]:
trainSub.info()
people.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2197291 entries, 0 to 2197290
Data columns (total 15 columns):
people_id            object
activity_id          object
date                 datetime64[ns]
activity_category    object
char_1               object
char_2               object
char_3               object
char_4               object
char_5               object
char_6               object
char_7               object
char_8               object
char_9               object
char_10              object
outcome              int64
dtypes: datetime64[ns](1), int64(1), object(13)
memory usage: 251.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189118 entries, 0 to 189117
Data columns (total 41 columns):
people_id    189118 non-null object
char_1       189118 non-null object
group_1      189118 non-null object
char_2       189118 non-null object
date         189118 non-null datetime64[ns]
char_3       189118 non-null object
char_4       189118 non-null object
char_5       189118 non-null object
char_6       189118 non-null object
char_7       189118 non-null object
char_8       189118 non-null object
char_9       189118 non-null object
char_10      189118 non-null bool
char_11      189118 non-null bool
char_12      189118 non-null bool
char_13      189118 non-null bool
char_14      189118 non-null bool
char_15      189118 non-null bool
char_16      189118 non-null bool
char_17      189118 non-null bool
char_18      189118 non-null bool
char_19      189118 non-null bool
char_20      189118 non-null bool
char_21      189118 non-null bool
char_22      189118 non-null bool
char_23      189118 non-null bool
char_24      189118 non-null bool
char_25      189118 non-null bool
char_26      189118 non-null bool
char_27      189118 non-null bool
char_28      189118 non-null bool
char_29      189118 non-null bool
char_30      189118 non-null bool
char_31      189118 non-null bool
char_32      189118 non-null bool
char_33      189118 non-null bool
char_34      189118 non-null bool
char_35      189118 non-null bool
char_36      189118 non-null bool
char_37      189118 non-null bool
char_38      189118 non-null int64
dtypes: bool(28), datetime64[ns](1), int64(1), object(11)
memory usage: 23.8+ MB

In [71]:
mergedTrain = trainSub.merge(right=people,on="people_id")
#mergedTrain['duration'] = mergedTrain.apply(mergedTrain[d].max() - mergedTrain[d].min())

In [72]:
mergedTrain.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2197291 entries, 0 to 2197290
Data columns (total 55 columns):
people_id            object
activity_id          object
date_x               datetime64[ns]
activity_category    object
char_1_x             object
char_2_x             object
char_3_x             object
char_4_x             object
char_5_x             object
char_6_x             object
char_7_x             object
char_8_x             object
char_9_x             object
char_10_x            object
outcome              int64
char_1_y             object
group_1              object
char_2_y             object
date_y               datetime64[ns]
char_3_y             object
char_4_y             object
char_5_y             object
char_6_y             object
char_7_y             object
char_8_y             object
char_9_y             object
char_10_y            bool
char_11              bool
char_12              bool
char_13              bool
char_14              bool
char_15              bool
char_16              bool
char_17              bool
char_18              bool
char_19              bool
char_20              bool
char_21              bool
char_22              bool
char_23              bool
char_24              bool
char_25              bool
char_26              bool
char_27              bool
char_28              bool
char_29              bool
char_30              bool
char_31              bool
char_32              bool
char_33              bool
char_34              bool
char_35              bool
char_36              bool
char_37              bool
char_38              int64
dtypes: bool(28), datetime64[ns](2), int64(2), object(23)
memory usage: 528.1+ MB

In [73]:
#data = data.fillna("nop")
mergedTrain = mergedTrain.fillna("nop")
#mergedTrain.info()

In [74]:
#mergedTrain["char_1_x"].unique()
from sklearn import preprocessing
LabelEncoder = preprocessing.LabelEncoder
#for i in mergedTrain:
#    if  :
#        print(mergedTrain[i])
        #mergedTrain[i] = le.fit_transform(mergedTrain[i])
mergedTrain = mergedTrain.apply(LabelEncoder().fit_transform)
for d in ['date_x', 'date_y']:
    mergedTrain['duration'] = mergedTrain[d].max() - mergedTrain[d].min()

In [75]:
mergedTrain = mergedTrain.drop(["people_id",'activity_id'],axis=1)
mergedTrain.head()

,date_x,activity_category,char_1_x,char_2_x,char_3_x,char_4_x,char_5_x,char_6_x,char_7_x,char_8_x,...,char_30,char_31,char_32,char_33,char_34,char_35,char_36,char_37,char_38,duration
0,405,3,0,0,0,0,0,0,0,0,...,1,1,0,0,1,1,1,0,36,1195
1,72,1,0,0,0,0,0,0,0,0,...,1,1,0,0,1,1,1,0,36,1195
2,72,1,0,0,0,0,0,0,0,0,...,1,1,0,0,1,1,1,0,36,1195
3,383,1,0,0,0,0,0,0,0,0,...,1,1,0,0,1,1,1,0,36,1195
4,405,1,0,0,0,0,0,0,0,0,...,1,1,0,0,1,1,1,0,36,1195

In [76]:
#from sklearn.feature_selection import SelectKBest
#from sklearn.feature_selection import chi2

#X_new,y_new = SelectKBest(chi2, k=10).fit_transform(X, y),
#print(X_new.shape)

X,y = mergedTrain.drop(["outcome"], axis=1),mergedTrain["outcome"]
print(X.shape)
print(y.shape)

(2197291, 53)
(2197291,)

In [78]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1,test_size=.4)
#X_new_train, X_new_test, y_new_train, y_new_test = train_test_split(X_new, y, random_state=1,test_size=.4)

In [79]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.pipeline import Pipeline

# Models we will use
gbm = GradientBoostingClassifier()
rbm = BernoulliRBM(random_state=0, verbose=True)

classifier = Pipeline(steps=[('rbm', rbm), ('gbm', gbm)])

###############################################################################
# Training

# Hyper-parameters. These were set by cross-validation,
# using a GridSearchCV. Here we are not performing cross-validation to
# save time.
rbm.learning_rate = 0.06
rbm.n_iter = 20
# More components tend to give better prediction performance, but larger
# fitting time
rbm.n_components = 100
gbm.n_estimators=50

# Training RBM-Logistic Pipeline
classifier.fit(X_train, y_train)

# Training Logistic regression
#gbm_classifier = GradientBoostingClassifier()
#gbm_classifier.fit(X_train, y_train)

[BernoulliRBM] Iteration 1, pseudo-likelihood = -170831759.29, time = 87.25s
[BernoulliRBM] Iteration 2, pseudo-likelihood = -341663430.95, time = 166.24s
[BernoulliRBM] Iteration 3, pseudo-likelihood = -512495129.71, time = 151.85s
[BernoulliRBM] Iteration 4, pseudo-likelihood = -683326816.85, time = 158.94s
[BernoulliRBM] Iteration 5, pseudo-likelihood = -854158517.53, time = 154.88s
[BernoulliRBM] Iteration 6, pseudo-likelihood = -1024990206.57, time = 155.59s
[BernoulliRBM] Iteration 7, pseudo-likelihood = -1195821897.23, time = 156.61s
[BernoulliRBM] Iteration 8, pseudo-likelihood = -1366653603.99, time = 7365.77s
[BernoulliRBM] Iteration 9, pseudo-likelihood = -1537485290.75, time = 11424.67s
[BernoulliRBM] Iteration 10, pseudo-likelihood = -1708316993.88, time = 9641.15s
[BernoulliRBM] Iteration 11, pseudo-likelihood = -1879148680.59, time = 161.99s
[BernoulliRBM] Iteration 12, pseudo-likelihood = -2049980376.22, time = 152.03s
[BernoulliRBM] Iteration 13, pseudo-likelihood = -2220812053.99, time = 149.90s
[BernoulliRBM] Iteration 14, pseudo-likelihood = -2391643745.33, time = 150.88s
[BernoulliRBM] Iteration 15, pseudo-likelihood = -2562475439.65, time = 157.16s
[BernoulliRBM] Iteration 16, pseudo-likelihood = -2733307148.53, time = 171.67s
[BernoulliRBM] Iteration 17, pseudo-likelihood = -2904138833.23, time = 171.69s
[BernoulliRBM] Iteration 18, pseudo-likelihood = -3074970529.62, time = 155.28s
[BernoulliRBM] Iteration 19, pseudo-likelihood = -3245802224.35, time = 149.72s
[BernoulliRBM] Iteration 20, pseudo-likelihood = -3416633903.93, time = 155.53s
[BernoulliRBM] Iteration 21, pseudo-likelihood = -3587465606.19, time = 152.21s
[BernoulliRBM] Iteration 22, pseudo-likelihood = -3758297299.64, time = 167.00s
[BernoulliRBM] Iteration 23, pseudo-likelihood = -3929128999.06, time = 164.06s
[BernoulliRBM] Iteration 24, pseudo-likelihood = -4099960689.69, time = 164.76s
[BernoulliRBM] Iteration 25, pseudo-likelihood = -4270792376.86, time = 175.42s
[BernoulliRBM] Iteration 26, pseudo-likelihood = -4441624077.05, time = 170.99s
[BernoulliRBM] Iteration 27, pseudo-likelihood = -4612455773.79, time = 171.58s
[BernoulliRBM] Iteration 28, pseudo-likelihood = -4783287451.66, time = 153.86s
[BernoulliRBM] Iteration 29, pseudo-likelihood = -4954119154.62, time = 158.19s
[BernoulliRBM] Iteration 30, pseudo-likelihood = -5124950845.75, time = 168.07s

Pipeline(steps=[('rbm', BernoulliRBM(batch_size=10, learning_rate=0.06, n_components=300, n_iter=30,
       random_state=0, verbose=True)), ('gbm', GradientBoostingClassifier(init=None, learning_rate=0.1, loss='deviance',
              max_depth=3, max_features=None, max_leaf_nodes=None,
              min_sa...      presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False))])

In [90]:
y_pred = classifier.predict(X_test)
print(metrics.classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.56      1.00      0.71    488226
          1       0.00      0.00      0.00    390691

avg / total       0.31      0.56      0.40    878917

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/metrics/classification.py:1074: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [91]:
#from sklearn import metrics
#rf = GradientBoostingClassifier(n_estimators=2000) #oob_score=True, n_estimators=20
#rfk = RandomForestClassifier(oob_score=True, n_estimators=20)

#rf.fit(X_train, y_train)
#y_pred = gbm.predict(X_test)
#print(metrics.accuracy_score(y_test, y_pred))

#rfk.fit(X_new_train, y_new_train)
#y_new_pred = rfk.predict(X_new_test)
#print(metrics.accuracy_score(y_new_test, y_new_pred))

In [92]:
test.head()

,date_x,activity_category,char_1_x,char_2_x,char_3_x,char_4_x,char_5_x,char_6_x,char_7_x,char_8_x,...,char_30,char_31,char_32,char_33,char_34,char_35,char_36,char_37,char_38,duration
0,3,0,42,2,7,1,6,1,1,16,...,1,1,1,1,1,1,1,1,76,1175
1,3,4,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,76,1175
2,89,0,4,1,7,4,6,1,1,5,...,1,1,1,1,1,1,1,1,90,1175
3,133,0,13,2,7,4,6,1,1,14,...,1,1,1,1,1,1,1,1,90,1175
4,90,4,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,90,1175

In [93]:
test = test.fillna("nop")
test = test.merge(right=people,on="people_id")
test = test.drop(["people_id",'activity_id'],axis=1)
test = test.apply(LabelEncoder().fit_transform)

for d in ['date_x', 'date_y']:
    test['duration'] = test[d].max() - test[d].min()

KeyError: 'people_id'

In [94]:
test.head()

,date_x,activity_category,char_1_x,char_2_x,char_3_x,char_4_x,char_5_x,char_6_x,char_7_x,char_8_x,...,char_30,char_31,char_32,char_33,char_34,char_35,char_36,char_37,char_38,duration
0,3,0,42,2,7,1,6,1,1,16,...,1,1,1,1,1,1,1,1,76,1175
1,3,4,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,76,1175
2,89,0,4,1,7,4,6,1,1,5,...,1,1,1,1,1,1,1,1,90,1175
3,133,0,13,2,7,4,6,1,1,14,...,1,1,1,1,1,1,1,1,90,1175
4,90,4,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,90,1175

In [95]:
fuit = classifier.predict(test)

In [96]:
#test = test.apply(LabelEncoder().inverse_transform)
submission = pd.DataFrame(act)


submission['outcome'] = fuit

In [98]:
submission['outcome'].unique()

array([0])

In [89]:
submission.to_csv('submission.csv',index=False)